services:
  - type: web
    name: nsfw-gen-bot
    env: python
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        fromSecret: TELEGRAM_TOKEN
      - key: REPLICATE_API_TOKEN
        fromSecret: REPLICATE_API_TOKEN